KFold cross validation allows us to evaluate performance of a model by creating K folds of given dataset. This is better then traditional train_test_split.

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [27]:
import warnings
warnings.filterwarnings('ignore')

LR=LogisticRegression()
LR.fit(X_train,y_train)
LR.score(X_test,y_test)

0.9629629629629629

In [7]:
SVM=SVC()
SVM.fit(X_train,y_train)
SVM.score(X_test,y_test)

0.9888888888888889

In [8]:
RF=RandomForestClassifier(n_estimators=10)
RF.fit(X_train,y_train)
RF.score(X_test,y_test)

0.9222222222222223

**Modularizing the code**

In [12]:
# KF fold split on digits data
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [13]:
get_score(LR,X_train,X_test,y_train,y_test)

C:\Users\satin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [14]:
get_score(SVM,X_train,X_test,y_train,y_test)

0.9888888888888889

In [15]:
get_score(RF,X_train,X_test,y_train,y_test)

0.9481481481481482

In [10]:
from sklearn.model_selection import KFold
KF=KFold(n_splits=3)
KF

KFold(n_splits=3, random_state=None, shuffle=False)

In [11]:
# providing the fake data to KF split
for train_index,test_index in KF.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [16]:
# now using stratified methods better than KF it randomize the data for uniform data spliting among catogories
from sklearn.model_selection import StratifiedKFold
SKF=StratifiedKFold(n_splits=3)

In [23]:
import warnings
warnings.filterwarnings('ignore')


scores_SVM=[]
scores_RF=[]
scores_LR=[]

for train_index,test_index in KF.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
                                  digits.target[train_index],digits.target[test_index]
    scores_LR.append(get_score(LR,X_train,X_test,y_train,y_test))
    scores_SVM.append(get_score(SVM,X_train,X_test,y_train,y_test))
    scores_RF.append(get_score(RF,X_train,X_test,y_train,y_test))

In [20]:
scores_LR

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [21]:
scores_SVM

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [22]:
scores_RF

[0.8731218697829716, 0.8931552587646077, 0.8981636060100167]

In [28]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [29]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [31]:
from sklearn.model_selection import cross_val_score
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.92777778, 0.89722222, 0.95821727, 0.9637883 , 0.92200557])

In [32]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.91944444, 0.94722222, 0.95821727, 0.96657382, 0.91643454])

**Excercise Description**
Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

- Logistic Regression
- SVM
- Decision Tree
- Random Forest

In [35]:
from sklearn.datasets import load_iris
iris=load_iris()
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [36]:
from sklearn.model_selection import cross_val_score

In [38]:
cross_val_score(LogisticRegression(),iris.data,iris.target)

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [39]:
cross_val_score(SVC(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [49]:
cross_val_score(SVC(C=10),iris.data,iris.target)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [40]:
cross_val_score(RandomForestClassifier(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [42]:
cross_val_score(RandomForestClassifier(n_estimators=10),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.86666667, 1.        , 1.        ])

In [43]:
cross_val_score(RandomForestClassifier(n_estimators=20),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [48]:
cross_val_score(RandomForestClassifier(n_estimators=30),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [41]:
from sklearn.tree import DecisionTreeClassifier
cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])